### PR TITLE
Table width adapts to terminal width

### PR DESCRIPTION
**Pull request by Ben-Baert**
The width of the table will change depending on the terminal width. If the terminal is too small to output at least one date column, a warning will be echoed.

All tests passing.

### CODE REVIEW

**Comment by codito** [comment]
Many thanks, it was super quick :)

May be we should a test for this? Looks good otherwise.

**Comment by Ben-Baert** [comment]
I agree, but I'm not really sure about how to write a test for this. I don't know how to set the terminal width in these tests. I'd like to write a test where I set width = 29 -> error message, width = 30 -> 1 date, width = 40 -> 2 dates, etc., but that means I need to test for different terminal widths, and as far as I know, the click test runner doesn't seem to provide this functionality.

Maybe some kind of Selenium for terminal where you can set the window size would be good? Although I'm not entirely sure whether something like that exists.

Any suggestions are welcome!

**Comment by codito** [comment]
We can set `habito.TERMINAL_WIDTH = 29` within the test case to simulate the error case. The simple positive scenario is already tested with existing test (habito.list should return zero). I think click sets terminal width to 80 in test runner by default.

Detailed positive tests may need indirect testing. E.g. we could test the output contains `today's date` and `tomorrow's date` for the scenario where we expect 2 dates to be output.

**Comment by Ben-Baert** [comment]
I wrote some tests that cover everything based on your suggestion, but I have this weird issue that expect(...).to.contain(...) always returns True (not just in the test case I just wrote, but in general). I don't really know why that happens. I run my tests with py.test.

**Comment by codito** [comment]
:+1: Thanks

I'm able to repro the expect..contain issue, it looks like a bug in sure. Merging this pr, we can fix expect..contain to use expect..match separately.

**Comment by codito** [comment]
Created https://github.com/gabrielfalcao/sure/issues/104 for the expect..contains issue.

**Comment by timofurrer** [comment]
I just fixed this issue with https://github.com/gabrielfalcao/sure/pull/110

Should be released shortly.

**Comment by timofurrer** [comment]
The fix is released in `sure`s version `1.3.0`. Thanks @codito for reporting!

**Pull request merged**
